# Generated by Django 2.2.7 on 2019-11-10 22:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user1', 'user2')},
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('event', 'guest')},
        ),
    ]
