# Generated by Django 2.2.7 on 2019-11-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating_count',
        ),
    ]
