# Generated by Django 2.2.7 on 2019-11-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_app', '0002_auto_20191107_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=15),
        ),
    ]
