# Generated by Django 2.2.7 on 2019-11-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_app', '0004_auto_20191107_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
