# Generated by Django 2.2.7 on 2019-11-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_app', '0005_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
