# Generated by Django 2.2.7 on 2019-11-08 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_app', '0007_auto_20191108_0043'),
        ('project_2_app', '0007_auto_20191108_0047'),
    ]

    operations = [
    ]
